### ISSUE TITLE
In readme, what's the difference between action plan styles?

### ISSUE THREAD

**Issue by hoopes** [StevenLambion/SwiftDux#29]
Hi, sorry if this is not the right forum for "tech support" - if there's a better place to ask (stack overflow?), please let me know, and I'll switch.

https://github.com/StevenLambion/SwiftDux#action-plans

Here, there is the `Dispatch Multiple Actions` and `Publish actions to the store` sections - what is the difference? In both case, the set of actions gets called, correct?

Thanks again...

**Comment by StevenLambion** [comment]
It might need a better explanation.

The action plans are a way to incapsulate multiple actions together. A common use case is an action that needs to update disconnected parts of the state, so it internally dispatches two actions for each part.

The "multiple actions" example is for the above use case.

The other example is more useful if you need to work with Combine publishers. For example, you need to retrieve data from an external service. Reducers are expected to be synchronous (on the main thread). This makes it difficult to work with asynchronous logic. If you've used Redux, it also had this problem. They solved it with middleware called "thunks" that allow promise based actions. SwiftDux solves it by supporting Combine inside of action plans.

The below example shows how users might be retrieved in an asynchronous action plan. The `UserService` has a method that returns a Combine publisher of users. We map the array of users to an action. Then we use the `send(to:receivedCompletion:)` to dispatch it. That method provides a cancellable object which the action plan can return. This allows SwiftDux to manage the cancellable for you, but you can choose to manage it yourself. Unfortunately, the cancellable has no indicator that the publisher ever completed. To solve this, the second parameter, "completed", must be provided to the method. This tells SwiftDux when the publisher has finished. Otherwise the cancellable won't be properly cleaned up, leading to a memory leak.

```swift
ActionPlan<AppState> { store, completed in
  UserService
    .getAllUsers()
    .map { UserActions.setUsers($0) }
    .receive(on: RunLoop.main)
    .send(to: store, receivedCompletion: completed)
}
```
